name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gcc:latest # or another pre-built image with your requirements

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run Tests
      run: make check

    - name: Validate Distribution
      run: make distcheck
